name: demoFlow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
        
      name:
        description: 'Person name'
        default: 'Team'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bulding"
  test:
    runs-on: DESKTOP-FLGRB30
    needs: build
    environment: dev
    steps:
      - name: Echo
        run: echo "Hello, ${{ matrix.environment}} ${{ vars.SERVICE_ACCOUNT }}"; echo " ${{ matrix.environment }} ${{ vars.SERVICE_ACCOUNT }} ">> $GITHUB_STEP_SUMMARY

  load-test:
    runs-on: DESKTOP-FLGRB30
    if: github.event_name == 'workflow_dispatch'
    needs: build
    environment: test
    steps:
      - name: sleepy
        run: |
          echo "testing 1,2,3"
  production:
    runs-on: DESKTOP-FLGRB30
    if: github.event.inputs.environment == 'qa'
    needs: [test,load-test]
    environment: 
      name: qa
      url: https://writeabout.net
    steps:
      - run: echo " step 1 " ; tree
      - run: echo " step 2 " ; sleep 5
      - run: echo " step 3 " ; sleep 5
      - run: echo " step 4 " ; sleep 5
      - run: echo " step 5 " ; sleep 5      
    
