name: demoFlow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person name'
        default: 'Team'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Hello, ${{ github.event.inputs.name }}!"

