name: test demo

on: 
  workflow_dispatch:
    inputs:
      namefield:
        type: choice
        options:
          - attendees
          - team
          - world
        

jobs:
  Step1:
    runs-on: ubuntu-latest

    steps:
      - name: step1
        run:  echo "hello ${{ github.event.inputs.namefield }}!" ; echo "hello ${{ github.event.inputs.namefield }}!" >> $GITHUB_STEP_SUMMARY

